<a href="https://colab.research.google.com/github/kazakov7/ai-foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd

In [33]:
malumot = {
    'Ism': ['Ali', 'Vali', 'Sami', 'Guli'],
    'Yosh': [20, 25, 30, 22],
    'Shahar': ['Toshkent', 'Samarqand', 'Buxoro', 'Toshkent'],
    'Maosh': [500, 800, 1200, 600]
}
df = pd.DataFrame(malumot)
print(df)

    Ism  Yosh     Shahar  Maosh
0   Ali    20   Toshkent    500
1  Vali    25  Samarqand    800
2  Sami    30     Buxoro   1200
3  Guli    22   Toshkent    600

In [35]:
df.head(2)

    Ism  Yosh     Shahar  Maosh
0   Ali    20   Toshkent    500
1  Vali    25  Samarqand    800

In [38]:
df.tail(2)

    Ism  Yosh    Shahar  Maosh
2  Sami    30    Buxoro   1200
3  Guli    22  Toshkent    600

In [39]:
df.shape

(4, 4)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ism     4 non-null      object
 1   Yosh    4 non-null      int64
 2   Shahar  4 non-null      object
 3   Maosh   4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [41]:
df.describe()

            Yosh        Maosh
count   4.000000     4.000000
mean   24.250000   775.000000
std     4.349329   309.569594
min    20.000000   500.000000
25%    21.500000   575.000000
50%    23.500000   700.000000
75%    26.250000   900.000000
max    30.000000  1200.000000

In [49]:
df = pd.DataFrame({
    'Ism': ['Ali', 'Vali', 'Sami', 'Guli'],
    'Yosh': [20, 25, 30, 22],
    'Maosh': [500, 800, 1200, 600]
})
print(df)

    Ism  Yosh  Maosh
0   Ali    20    500
1  Vali    25    800
2  Sami    30   1200
3  Guli    22    600

In [50]:
print(df.loc[1:,"Ism"])

1    Vali
2    Sami
3    Guli
Name: Ism, dtype: object

In [55]:
print(df.iloc[0:2])

    Ism  Yosh  Maosh
0   Ali    20    500
1  Vali    25    800

In [56]:
print(df.iloc[0:2, 0:2])

    Ism  Yosh
0   Ali    20
1  Vali    25

In [59]:
df[df["Yosh"]>22]

    Ism  Yosh  Maosh
1  Vali    25    800
2  Sami    30   1200

In [63]:
df[df["Ism"]=="Sami"]

    Ism  Yosh  Maosh
2  Sami    30   1200

In [64]:
df.sum()

Ism      AliValiSamiGuli
Yosh                  97
Maosh               3100
dtype: object

In [65]:
df.sum(numeric_only=True)

Yosh       97
Maosh    3100
dtype: int64

In [68]:
df.count()

Ism      4
Yosh     4
Maosh    4
dtype: int64

In [86]:
df = pd.DataFrame({
    'Ism': ['Ali', 'Vali', 'Sami', 'Guli'],
    'Yosh': [20, None, 30, 22],
    'Maosh': [500, 800, None, 600]
})
df

    Ism  Yosh  Maosh
0   Ali  20.0  500.0
1  Vali   NaN  800.0
2  Sami  30.0    NaN
3  Guli  22.0  600.0

In [81]:
df.isnull().sum()

Ism      0
Yosh     1
Maosh    1
dtype: int64

In [84]:
df.dropna(subset=['Yosh'])

    Ism  Yosh  Maosh
0   Ali  20.0  500.0
2  Sami  30.0    NaN
3  Guli  22.0  600.0

In [89]:
df.fillna({"Yosh":1, "Maosh":0})

    Ism  Yosh  Maosh
0   Ali  20.0  500.0
1  Vali   1.0  800.0
2  Sami  30.0    0.0
3  Guli  22.0  600.0

In [ ]:
df=pd.read_csv("smartphone.ipynb")
print(df.head())